### ISSUE TITLE
Loading gem fails on missing VirtualAssembly::Semantizer

### ISSUE THREAD

**Issue by mkllnk** [datafoodconsortium/connector-ruby#1]
I added the gem and ran `bundle`. Then running the Rails console fails:

```
$ bundle exec rails console
/home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- virtual_assembly/semantizer (LoadError)
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/datafoodconsortium-connector-1.0.0.pre.alpha/lib/datafoodconsortium/connector/json_ld_serializer.rb:23:in `<main>'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
...
```

The same happens if I use plain Ruby:

```
$ ruby -e "require 'datafoodconsortium/connector'"
<internal:/home/maikel/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- virtual_assembly/semantizer (LoadError)
	from <internal:/home/maikel/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/maikel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/datafoodconsortium-connector-1.0.0.pre.alpha/lib/datafoodconsortium/connector/json_ld_serializer.rb:23:in `<top (required)>'
	from <internal:/home/maikel/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

**Comment by lecoqlibre** [comment]
@mkllnk Did you install `virtual_assembly-semantizer`? Bundle should have installed it for you but I may have miscounfigured the gemfile.

See https://rubygems.org/gems/virtual_assembly-semantizer.

**Comment by mkllnk** [comment]
`bundle update datafoodconsortium-connector` solved this for me. :+1:
